// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'BURAYA_WEB_API_KEY_YAZIN',
    appId: 'BURAYA_WEB_APP_ID_YAZIN',
    messagingSenderId: 'BURAYA_MESSAGING_SENDER_ID_YAZIN',
    projectId: 'BURAYA_PROJECT_ID_YAZIN',
    authDomain: 'BURAYA_AUTH_DOMAIN_YAZIN',
    storageBucket: 'BURAYA_STORAGE_BUCKET_YAZIN',
    measurementId: 'BURAYA_MEASUREMENT_ID_YAZIN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'BURAYA_ANDROID_API_KEY_YAZIN',
    appId: 'BURAYA_ANDROID_APP_ID_YAZIN',
    messagingSenderId: 'BURAYA_MESSAGING_SENDER_ID_YAZIN',
    projectId: 'BURAYA_PROJECT_ID_YAZIN',
    storageBucket: 'BURAYA_STORAGE_BUCKET_YAZIN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'BURAYA_IOS_API_KEY_YAZIN',
    appId: 'BURAYA_IOS_APP_ID_YAZIN',
    messagingSenderId: 'BURAYA_MESSAGING_SENDER_ID_YAZIN',
    projectId: 'BURAYA_PROJECT_ID_YAZIN',
    storageBucket: 'BURAYA_STORAGE_BUCKET_YAZIN',
    iosClientId: 'BURAYA_IOS_CLIENT_ID_YAZIN',
    iosBundleId: 'com.example.ozelChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'BURAYA_MACOS_API_KEY_YAZIN',
    appId: 'BURAYA_MACOS_APP_ID_YAZIN',
    messagingSenderId: 'BURAYA_MESSAGING_SENDER_ID_YAZIN',
    projectId: 'BURAYA_PROJECT_ID_YAZIN',
    storageBucket: 'BURAYA_STORAGE_BUCKET_YAZIN',
    iosClientId: 'BURAYA_MACOS_CLIENT_ID_YAZIN',
    iosBundleId: 'com.example.ozelChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'BURAYA_WINDOWS_API_KEY_YAZIN',
    appId: 'BURAYA_WINDOWS_APP_ID_YAZIN',
    messagingSenderId: 'BURAYA_MESSAGING_SENDER_ID_YAZIN',
    projectId: 'BURAYA_PROJECT_ID_YAZIN',
    authDomain: 'BURAYA_AUTH_DOMAIN_YAZIN',
    storageBucket: 'BURAYA_STORAGE_BUCKET_YAZIN',
    measurementId: 'BURAYA_MEASUREMENT_ID_YAZIN',
  );
}